### ISSUE TITLE
open printerdocument ESX

### ISSUE THREAD

**Issue by nemaDev** [WaypointRP/wp-printer#1]
everything works but when using the printed document, it doesn't open in ESX latest version, also using ox_inventory

**Comment by BackSH00TER** [comment]
Hi @nemaDev this is because I only added default ESX support for addItem which does not support item metadata. An OX specific solution would need to be added to the framework file for this to work. 

More than happy to receive contributions from the community via pull requests to add this functionality. This is not a top priority for me tho, so it will be some time (_if ever_) before I find time to get around to this.

**Comment by BackSH00TER** [comment]
@nemaDev this should be fixed by the following commit: https://github.com/WaypointRP/wp-printer/commit/aee7055fff5a53746c47bebcfe7f9ea071d25dd8

Pull v1.0.1 and let me know if it fixes the issue for you. I verified in qb + ox, but did not test with esx + ox, can you test and see if it fixes for you?

**Comment by nemaDev** [comment]
just updated ox_inventory and when using the printer I got kicked out of the server. here is this thread to see a solution.

https://discord.com/channels/813030955598086174/1191448114792509570

**Comment by nemaDev** [comment]
for now i commented the dropplayer line of ox inventory and i was able to use the printer. but i still can't use the printed document and i get this error

![image](https://github.com/WaypointRP/wp-printer/assets/28969108/0071ba34-39c4-4c6a-b4f2-0ac51edd774b)

**Comment by BackSH00TER** [comment]
@nemaDev Did you set `Config.Inventory == 'ox'` ?

Looks like this is the line erroring out
`    local documentUrl = itemMetadata.url ~= nil and itemMetadata.url or false`
Which means itemMetadata is still nil, you could do `    local documentUrl = (itemMetadata and itemMetadata.url ~= nil and itemMetadata.url) or false, which should get past the error, but if the metadata is not working the item will be pointless since the metadata is necessary to get the url. 

You could try putting a a console log in the framework file to see what item data is being logged. Looks like you're still not getting the metadata returned from the item data for some reason
```
function GetItemMetadata(itemData) 
-- ADD THIS PRINT HERE
print('GetItemMetadata', json.encode(itemData, {indent = true})
    if Config.Inventory == 'esx' then
        -- ESX inventory does not support metadata by default, recommended to use ox_inventory instead
        print("GetItemMetadata is missing an implementation in the framework file for esx")
    elseif Config.Inventory == 'qb' then
        return itemData.info
    elseif Config.Inventory == 'ox' then
        return itemData.metadata
    end
end
```

**Comment by nemaDev** [comment]
![image](https://github.com/WaypointRP/wp-printer/assets/28969108/23261e65-3854-44ee-8497-462e4e21535f)
print only the item name

maybe if you change how the item is taken? for example as I have another camera script? 

ox_inventory/modules/items/client.lua

```lua
Item('photo', function(data, slot)
    TriggerEvent('wert-camera:client:use-photo', slot.metadata.photourl)
end)
```

client
```lua
RegisterNetEvent("wert-camara:client:use-photo", function(url1)
    if not photoactive then
        photoactive = true
        SetNuiFocus(true, true)
        SendNUIMessage({action = "Show", photo = url1}) 
        local ped = cache.ped
        SharedRequestAnimDict("amb@world_human_tourist_map@male@base", function()
            TaskPlayAnim(ped, "amb@world_human_tourist_map@male@base", "base", 2.0, 2.0, -1, 1, 0, false, false, false)
        end)
        local x,y,z = table.unpack(GetEntityCoords(ped))
        if not HasModelLoaded("prop_tourist_map_01") then
            LoadPropDict("prop_tourist_map_01")
        end
        photoprop = CreateObject(GetHashKey("prop_tourist_map_01"), x, y, z+0.2,  true,  true, true)
        AttachEntityToEntity(photoprop, ped, GetPedBoneIndex(ped, 28422), 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, true, true, false, true, 1, true)
        SetModelAsNoLongerNeeded("prop_tourist_map_01")
    end
end)
```

server
```lua
RegisterNetEvent("wert-camara:server:add-photo-item", function(url, location)
    local time = os.date('*t')
    local ply = ESX.GetPlayerFromId(source)
    if ply then
        local info = {
            photourl = string.gsub(url, '\"', '"'),
            description = 'Foto tomada con Canon EOS M50  \n  Fecha y hora: ' .. time.day .. '/'  .. time.month .. '/' .. time.year .. ' - ' .. time.hour .. ':' .. time.min .. '  \n  Ubicacion: ' .. location
        }
        exports.ox_inventory:AddItem(source, 'photo', 1, info)
    end
end)
```

**Comment by BackSH00TER** [comment]
> ![image](https://private-user-images.githubusercontent.com/28969108/293619769-23261e65-3854-44ee-8497-462e4e21535f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjM0MzQsIm5iZiI6MTcwNDIyMzEzNCwicGF0aCI6Ii8yODk2OTEwOC8yOTM2MTk3NjktMjMyNjFlNjUtMzg1NC00NGVlLTg0OTctNDYyZTRlMjE1MzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE5MTg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZTVjZDMyMDAyZWNhMTc2YmVhNzA0ZmVlZDg3ZTk2NDNiNDFmNmJmMzIyZWFhMmMyY2M0ZGRlZWQxOTQ1NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u9EpY-ObdIqiqKviIhT8ySckrGz5nxeJlEHqs7oGILs)
> print only the item name

Okay we're making progress now. This clearly indicates the issue, the second arg `item` is only returning the itemName. 
For qb and qb + ox, `item` is a table containing all of this information
![image](https://github.com/WaypointRP/wp-printer/assets/18689469/043692c7-f49a-410e-863f-1c31e68c2160)

Spun up a quick test esx + ox server and found that there is a third arg that contains the additional item data
![image](https://github.com/WaypointRP/wp-printer/assets/18689469/a7fe8bb6-b16a-41de-bca9-52d5592c5eb7)

We'll just need to update the CreateUseableItem function to account for this in the callback function that it passes to RegisterUsableItem

**Comment by BackSH00TER** [comment]
@nemaDev  Pushed a fix for this https://github.com/WaypointRP/wp-printer/commit/a8b3bfb65f1b110a6b6cad78d213a780ca782cd6 

You can pull v1.0.2 and the issue should be fixed now. 

Tested the fix on qb, qb + ox, and esx + ox and it works correctly on all versions.

**Comment by nemaDev** [comment]
working perfect 
![image](https://github.com/WaypointRP/wp-printer/assets/28969108/8d1c2dbd-3aa8-4698-a260-29c607662115)
thank you very much for taking the time
